name: Tony Edwards
bio: Doer of things
picture: assets/images/headshot.jpg
description: A blog about my corner of the world# twitter summary info

url: https://tonyedwardspz.co.uk
permalink: /:categories/:title/

mastodon: https://mastodon.social/@tonyedwardspz
twitter: tonyedwardspz
instagram: tonyedwardspz
linkedin: tonyedwardspz
youtube: UCeUTkW7-_b0vbhV04SRb_2A
github: tonyedwardspz
stackoverflow: 3194491/tonyedwardspz
medium: tonyedwardspz

paginate: 12
paginate_path: "blog/:num/"
post-advance-links: [blog]

plugins:
  - jekyll-seo-tag
  #- jekyll-feed
  - jemoji
  - jekyll-paginate
  - jekyll-default-layout

plugins_dir:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - cache/
  - gems/
  - ruby/
