name: Tony Edwards
bio: Doer of things
picture: assets/images/headshot.jpg
picture-webp: assets/images/headshot.webp
description: A curation of learnings, musings and similarly captured day dreams.

url: https://tonyedwardspz.co.uk
permalink: /:categories/:title/

mastodon: https://mastodon.social/@tonyedwardspz
twitter: tonyedwardspz
instagram: tonyedwardspz
linkedin: tonyedwardspz
youtube: UCeUTkW7-_b0vbhV04SRb_2A
github: tonyedwardspz
stackoverflow: 3194491/tonyedwardspz

paginate: 18
paginate_path: "blog/:num/"
post-advance-links: [blog]

# SEO-Tag Overrides
locale: en_GB


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-default-layout

plugins_dir:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - cache/
  - gems/
  - ruby/
